Reenable all golangci linters and fix the remaining errors
Error were theses :

    >>--- RESULTS: GOLANGCI CODE ANALYSIS ---<<
    controller/pipeline_environments_blackbox_test.go:36:2: `prodCtrl` is unused (structcheck)
        prodCtrl *controller.PipelineEnvironmentController
        ^
    controller/pipeline_environments_blackbox_test.go:117:17: Error return value of `s.ctrl2.Create` is not checked (errcheck)
            s.ctrl2.Create(createCtxerr)
                          ^
    make: *** [analyze-go-code] Error 1

This closes openshiftio/openshift.io#4590 and closes #121